### ISSUE TITLE
Complete Presentation

### ISSUE THREAD

**Issue by nmarble** [chrisvarga/chatbot#10]
Complete presentation PowerPoint for submission.

[https://github.com/chrisvarga/chatbot/blob/master/Marble_Varga_Prop_Presentation.pptx](url)

**Comment by nmarble** [comment]
I will talk from the beginning to Other Work, if you want to talk from the methods until the end. Feel free to change the theme if you want I don't really care what it looks like.

Remember it should be only 5 min total, so if each of us talk about 2 min 30 seconds we should be fine. Also, we need to turn it in by tonight so let me know when you are done and I will submit it to his drop box thing.

**Comment by chrisvarga** [comment]
## Methods

* Use unsupervised learning algorithm (TBD) to group tweets
* Group into: Question, Answer, Comment, etc
* If input is a Question, respond with a tweet from Answer
* Pick best tweet by comparing number of same noun categories
* Example noun categories: Italian Food, Video Games, Computer Science

## Expected Results

* To test, will give a tweet as input
* If it responds with same response tweet as the real conversation, success

**Comment by nmarble** [comment]
Uploaded to dropbox
