### ISSUE TITLE
Proposal Implementation

### ISSUE THREAD

**Issue by nmarble** [chrisvarga/chatbot#5]
Write Proposal Implementation section (Section 3)

References here: #8

**Comment by chrisvarga** [comment]
(saving my work so far)

## Implementation
The overall strategy of our implementation can be summarized as follows. We begin by receiving a user inputted sentence through a command line interface. This sentence is classified into one of the eight broad categories provided by Ritter et al. [1], namely: Status, Question to Followers, Reference Broadcast, Question, Reaction, Comment, Answer, Response. We accomplish this classification by utilizing the Pattern python library from Smedt and Daelemans [2] to perform parts of speech tagging. A probability of the sentence being in each category is assigned using these tagged parts of speech, and the sentence will be placed in the category with the highest probability. Meanwhile, we will also maintain a continuously updating local database of Twitter messages which will be classified according to the same eight categories stated above. 

[flowchart of overall strategy somewhere in here]

Our chatbot will then search through our local database for tweets in the category which best corresponds to being a good response to the user input sentence. For example, if the input sentence is classified as a Question, then the chatbot will search for tweets in the Answer category. Each result from the list of returned tweets will then be ranked by assigning a value representing the level of similarity to the input sentence. This value ranking will utilize a formula based on the total number of common noun (NN) keywords that are in the same narrow category in each tweet. Examples of narrow categories are Italian Food, Video Games, or Computer Science. The chatbot will respond to the user input sentence with the highest ranked of these tweets in the database.

## References For This Section

[1] Ritter, A., Cherry, C., & Dolan, B. (2010, June). Unsupervised modeling of twitter conversations. In _Human Language Technologies: The 2010 Annual Conference of the North American Chapter of the Association for Computational Linguistics_ (pp. 172-180). Association for Computational Linguistics.

[2] Smedt, T. D., & Daelemans, W. (2012). Pattern for python. _Journal of Machine Learning Research_, 13(Jun), 2063-2067.

**Comment by nmarble** [comment]
The sentence, 
> We begin by receiving a user inputted sentence through a command line interface.
Sounds weird to me, I suggest something like:
> We begin by receiving a sentence from a user through a command line interface.

Also, I think the step of adding a locally maintained database may be unnecessary at this point but could be added for future work. If instead of storing the twitter messages permanently we can simply use what ever the query returns and search these results for the best response. This query should already be suited for the category of input from the user because the category is what determines how to make that query. 

It could be more accurate to use a database on top of new results for every query but I think it may be best to simply get a baseline down first with a working concept then add to it if we feel that we have time for extra things.

**Comment by chrisvarga** [comment]
Updated the command line interface sentence. About the database, fair enough. I thought it might be a good way to get around the limited tweets to get better results, but I agree it could be a nonessential feature until we have time for it.
